### ISSUE TITLE
Issues on coreos and kubernetes versions

### ISSUE THREAD

**Issue by draintank** [raintank/snap_k8s#3]
Hi, apparently the old patched tag for snap-plugin-collector-docker is not working anymore, it doesn't collect any data anymore, i tested the 9th tag from intelsdi-x and it did push data into my graphite deployment.
Is there a chance you could patch up the new tag to contain the namespace fixes? (the fs fix is already included in the release).
(I took an attempt for a fix, as you can see, but i can't manage to build a version that runs well)

Thanks in advanced.

**Comment by daniellee** [comment]
The snap-plugin-collector-docker is a bit of a sad story. It got refactored and the new version from intel uses a ton of memory which makes it unusable for us. We are planning to replace it with cAdvisor and I think one of the guys on the Grafana Labs - Hosted Metrics team is going to start on it this week.
